@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJleGFtcGxlNSIsImlhdCI6MTczMDMyNjk5M30.EXwSIC5kcbH9H3x8A-D4-winryN0zWkkifSVwgvaUlA

GET {{host}}/api/events

###
GET {{host}}/api/events/4

###
GET {{host}}/api/events/upcoming

###
GET {{host}}/api/events?type=futbol

###
GET {{host}}/api/events/date?from=2024-12-25&to=2025-01-10

###
POST {{host}}/api/events
Content-Type: application/json
Authorization: {{token}}

{
    "nombre": "Torneo de Petanca",
    "descripcion": "Gran torneo de Jubilados vs Prejubilados",
    "fecha": "2024-12-23",
    "ubicacion": "Alicante",
    "tipoDeporte": "Petanca",
    "organizador": "Federación Española de Petanca"
}

###
PUT {{host}}/api/events/21
Content-Type: application/json
Authorization: {{token}}

{
    "nombre": "Torneo de Tenis",
    "descripcion": "Final de Profesores vs Alumnos",
    "fecha": "2025-01-14",
    "ubicacion": "Mérida",
    "tipoDeporte": "Tenis",
    "organizador": "Federación Deportiva de Tenis"
}

###
DELETE {{host}}/api/events/21
Authorization: {{token}}

########################################
POST {{host}}/api/users/register
Content-Type: application/json

{
    "username": "example5",
    "password": "examplePassword"
}

###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "username": "example4",
    "password": "examplePassword"
}

###
GET {{host}}/api/users/profile
Authorization: {{token}}