@host = http://localhost:3000

GET {{host}}/api/events

###
GET {{host}}/api/events/4

###
GET {{host}}/api/events/upcoming

###
GET {{host}}/api/events?type=futbol

###
GET {{host}}/api/events/date?from=2024-12-25&to=2025-01-10

###
POST {{host}}/api/events
Content-Type: application/json

{
    "nombre": "Torneo de Petanca",
    "descripcion": "Gran torneo de Jubilados vs Prejubilados",
    "fecha": "2024-12-23",
    "ubicacion": "Alicante",
    "tipoDeporte": "Petanca",
    "organizador": "Federación Española de Petanca"
}

###
PUT {{host}}/api/events/21
Content-Type: application/json

{
    "nombre": "Torneo de Tenis",
    "descripcion": "Final de Profesores vs Alumnos",
    "fecha": "2025-01-14",
    "ubicacion": "Mérida",
    "tipoDeporte": "Tenis",
    "organizador": "Federación Deportiva de Tenis"
}

###
DELETE {{host}}/api/events/29